# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/mainUI.ui'
#
# Created: Tue Aug  4 00:20:08 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_guiDlg(object):
    def setupUi(self, guiDlg):
        guiDlg.setObjectName("guiDlg")
        guiDlg.resize(428, 845)
        self.verticalLayout = QtGui.QVBoxLayout(guiDlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtGui.QGroupBox(guiDlg)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.thBox = QtGui.QSpinBox(self.groupBox)
        self.thBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.thBox.setMaximum(10000)
        self.thBox.setSingleStep(10)
        self.thBox.setProperty("value", 350)
        self.thBox.setObjectName("thBox")
        self.gridLayout.addWidget(self.thBox, 2, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.aBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.aBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.aBox.setMinimum(-4.0)
        self.aBox.setMaximum(4.0)
        self.aBox.setSingleStep(0.05)
        self.aBox.setObjectName("aBox")
        self.gridLayout.addWidget(self.aBox, 2, 2, 1, 1)
        self.xBox = QtGui.QSpinBox(self.groupBox)
        self.xBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xBox.setMinimum(-10000)
        self.xBox.setMaximum(10000)
        self.xBox.setSingleStep(10)
        self.xBox.setProperty("value", 1000)
        self.xBox.setObjectName("xBox")
        self.gridLayout.addWidget(self.xBox, 2, 0, 1, 1)
        self.aLabel = QtGui.QLabel(self.groupBox)
        self.aLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.aLabel.setObjectName("aLabel")
        self.gridLayout.addWidget(self.aLabel, 1, 2, 1, 1)
        self.zLabel = QtGui.QLabel(self.groupBox)
        self.zLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.zLabel.setObjectName("zLabel")
        self.gridLayout.addWidget(self.zLabel, 1, 1, 1, 1)
        self.xLabel = QtGui.QLabel(self.groupBox)
        self.xLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xLabel.setObjectName("xLabel")
        self.gridLayout.addWidget(self.xLabel, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 3, 1, 1)
        self.zBox = QtGui.QSpinBox(self.groupBox)
        self.zBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.zBox.setMinimum(-10000)
        self.zBox.setMaximum(10000)
        self.zBox.setSingleStep(10)
        self.zBox.setProperty("value", 1000)
        self.zBox.setObjectName("zBox")
        self.gridLayout.addWidget(self.zBox, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.navigationButton = QtGui.QPushButton(self.groupBox)
        self.navigationButton.setObjectName("navigationButton")
        self.horizontalLayout.addWidget(self.navigationButton)
        self.ignoreAngle = QtGui.QCheckBox(self.groupBox)
        self.ignoreAngle.setObjectName("ignoreAngle")
        self.horizontalLayout.addWidget(self.ignoreAngle)
        self.positionsCombo = QtGui.QComboBox(self.groupBox)
        self.positionsCombo.setObjectName("positionsCombo")
        self.horizontalLayout.addWidget(self.positionsCombo)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(guiDlg)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 2, 1, 1)
        self.tyBox = QtGui.QSpinBox(self.groupBox_2)
        self.tyBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tyBox.setMinimum(680)
        self.tyBox.setMaximum(1000)
        self.tyBox.setSingleStep(10)
        self.tyBox.setProperty("value", 800)
        self.tyBox.setObjectName("tyBox")
        self.gridLayout_2.addWidget(self.tyBox, 3, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 1, 1, 1)
        self.txBox = QtGui.QSpinBox(self.groupBox_2)
        self.txBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txBox.setMaximum(350)
        self.txBox.setSingleStep(10)
        self.txBox.setProperty("value", 200)
        self.txBox.setObjectName("txBox")
        self.gridLayout_2.addWidget(self.txBox, 3, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 4, 2, 1, 1)
        self.tzBox = QtGui.QSpinBox(self.groupBox_2)
        self.tzBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tzBox.setMinimum(150)
        self.tzBox.setMaximum(350)
        self.tzBox.setSingleStep(10)
        self.tzBox.setProperty("value", 210)
        self.tzBox.setObjectName("tzBox")
        self.gridLayout_2.addWidget(self.tzBox, 3, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 4, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 4, 1, 1, 1)
        self.rxBox = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.rxBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rxBox.setMinimum(-4.0)
        self.rxBox.setMaximum(4.0)
        self.rxBox.setSingleStep(0.05)
        self.rxBox.setObjectName("rxBox")
        self.gridLayout_2.addWidget(self.rxBox, 5, 0, 1, 1)
        self.ryBox = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.ryBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ryBox.setMinimum(-4.0)
        self.ryBox.setMaximum(4.0)
        self.ryBox.setSingleStep(0.05)
        self.ryBox.setProperty("value", -1.57)
        self.ryBox.setObjectName("ryBox")
        self.gridLayout_2.addWidget(self.ryBox, 5, 1, 1, 1)
        self.rzBox = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.rzBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rzBox.setMinimum(-4.0)
        self.rzBox.setMaximum(4.0)
        self.rzBox.setSingleStep(0.05)
        self.rzBox.setProperty("value", -3.14)
        self.rzBox.setObjectName("rzBox")
        self.gridLayout_2.addWidget(self.rzBox, 5, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ikButton = QtGui.QPushButton(self.groupBox_2)
        self.ikButton.setObjectName("ikButton")
        self.horizontalLayout_2.addWidget(self.ikButton)
        self.vikButton = QtGui.QPushButton(self.groupBox_2)
        self.vikButton.setObjectName("vikButton")
        self.horizontalLayout_2.addWidget(self.vikButton)
        self.widget = QtGui.QWidget(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2.addWidget(self.widget)
        self.topButton = QtGui.QPushButton(self.groupBox_2)
        self.topButton.setObjectName("topButton")
        self.horizontalLayout_2.addWidget(self.topButton)
        self.lowButton = QtGui.QPushButton(self.groupBox_2)
        self.lowButton.setObjectName("lowButton")
        self.horizontalLayout_2.addWidget(self.lowButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_4 = QtGui.QGroupBox(guiDlg)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.ttsEdit = QtGui.QLineEdit(self.groupBox_4)
        self.ttsEdit.setObjectName("ttsEdit")
        self.horizontalLayout_3.addWidget(self.ttsEdit)
        self.sayButton = QtGui.QPushButton(self.groupBox_4)
        self.sayButton.setObjectName("sayButton")
        self.horizontalLayout_3.addWidget(self.sayButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_12 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(0, 25))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_4.addWidget(self.label_12)
        self.asrLabel = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.asrLabel.sizePolicy().hasHeightForWidth())
        self.asrLabel.setSizePolicy(sizePolicy)
        self.asrLabel.setMinimumSize(QtCore.QSize(0, 25))
        self.asrLabel.setText("")
        self.asrLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.asrLabel.setObjectName("asrLabel")
        self.horizontalLayout_4.addWidget(self.asrLabel)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_3 = QtGui.QGroupBox(guiDlg)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.shutdown1Button = QtGui.QPushButton(self.groupBox_3)
        self.shutdown1Button.setObjectName("shutdown1Button")
        self.verticalLayout_5.addWidget(self.shutdown1Button)
        self.temperatura1 = QtGui.QLabel(self.groupBox_3)
        self.temperatura1.setText("")
        self.temperatura1.setObjectName("temperatura1")
        self.verticalLayout_5.addWidget(self.temperatura1)
        self.horizontalLayout_7.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.reset1Button = QtGui.QPushButton(self.groupBox_3)
        self.reset1Button.setObjectName("reset1Button")
        self.verticalLayout_6.addWidget(self.reset1Button)
        self.loadavg1 = QtGui.QLabel(self.groupBox_3)
        self.loadavg1.setText("")
        self.loadavg1.setObjectName("loadavg1")
        self.verticalLayout_6.addWidget(self.loadavg1)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout_10.addLayout(self.horizontalLayout_7)
        self.wifi1 = QtGui.QLabel(self.groupBox_3)
        self.wifi1.setObjectName("wifi1")
        self.verticalLayout_10.addWidget(self.wifi1)
        self.horizontalLayout_8.addLayout(self.verticalLayout_10)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.shutdown2Button = QtGui.QPushButton(self.groupBox_3)
        self.shutdown2Button.setObjectName("shutdown2Button")
        self.verticalLayout_8.addWidget(self.shutdown2Button)
        self.temperatura2 = QtGui.QLabel(self.groupBox_3)
        self.temperatura2.setText("")
        self.temperatura2.setObjectName("temperatura2")
        self.verticalLayout_8.addWidget(self.temperatura2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_8)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.reset2Button = QtGui.QPushButton(self.groupBox_3)
        self.reset2Button.setObjectName("reset2Button")
        self.verticalLayout_7.addWidget(self.reset2Button)
        self.loadavg2 = QtGui.QLabel(self.groupBox_3)
        self.loadavg2.setText("")
        self.loadavg2.setObjectName("loadavg2")
        self.verticalLayout_7.addWidget(self.loadavg2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        self.wifi2 = QtGui.QLabel(self.groupBox_3)
        self.wifi2.setObjectName("wifi2")
        self.verticalLayout_9.addWidget(self.wifi2)
        self.horizontalLayout_8.addLayout(self.verticalLayout_9)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_5 = QtGui.QGroupBox(guiDlg)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.featureNavigation = QtGui.QCheckBox(self.groupBox_5)
        self.featureNavigation.setChecked(True)
        self.featureNavigation.setObjectName("featureNavigation")
        self.horizontalLayout_6.addWidget(self.featureNavigation)
        self.featureManupulation = QtGui.QCheckBox(self.groupBox_5)
        self.featureManupulation.setChecked(True)
        self.featureManupulation.setObjectName("featureManupulation")
        self.horizontalLayout_6.addWidget(self.featureManupulation)
        self.featureSpeech = QtGui.QCheckBox(self.groupBox_5)
        self.featureSpeech.setChecked(True)
        self.featureSpeech.setObjectName("featureSpeech")
        self.horizontalLayout_6.addWidget(self.featureSpeech)
        self.featureSystem = QtGui.QCheckBox(self.groupBox_5)
        self.featureSystem.setChecked(True)
        self.featureSystem.setObjectName("featureSystem")
        self.horizontalLayout_6.addWidget(self.featureSystem)
        self.verticalLayout.addWidget(self.groupBox_5)

        self.retranslateUi(guiDlg)
        QtCore.QMetaObject.connectSlotsByName(guiDlg)

    def retranslateUi(self, guiDlg):
        guiDlg.setWindowTitle(QtGui.QApplication.translate("guiDlg", "shellyPanel", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("guiDlg", "Navigation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("guiDlg", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">z</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("guiDlg", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">angle</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("guiDlg", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">x</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.aLabel.setText(QtGui.QApplication.translate("guiDlg", "a", None, QtGui.QApplication.UnicodeUTF8))
        self.zLabel.setText(QtGui.QApplication.translate("guiDlg", "z", None, QtGui.QApplication.UnicodeUTF8))
        self.xLabel.setText(QtGui.QApplication.translate("guiDlg", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("guiDlg", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">threshold</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.navigationButton.setText(QtGui.QApplication.translate("guiDlg", "go", None, QtGui.QApplication.UnicodeUTF8))
        self.ignoreAngle.setText(QtGui.QApplication.translate("guiDlg", "ignore\n"
"angle", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("guiDlg", "Manipulation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("guiDlg", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">tz</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("guiDlg", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">ty</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("guiDlg", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">rz</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("guiDlg", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">rx</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("guiDlg", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">tx</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("guiDlg", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">ry</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.ikButton.setText(QtGui.QApplication.translate("guiDlg", "go\n"
"IK", None, QtGui.QApplication.UnicodeUTF8))
        self.vikButton.setText(QtGui.QApplication.translate("guiDlg", "go\n"
"VIK", None, QtGui.QApplication.UnicodeUTF8))
        self.topButton.setText(QtGui.QApplication.translate("guiDlg", "top\n"
"position", None, QtGui.QApplication.UnicodeUTF8))
        self.lowButton.setText(QtGui.QApplication.translate("guiDlg", "low\n"
"position", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("guiDlg", "Speech synthesis and recognition", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("guiDlg", "Synthesis", None, QtGui.QApplication.UnicodeUTF8))
        self.sayButton.setText(QtGui.QApplication.translate("guiDlg", "say", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("guiDlg", "Recognition:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("guiDlg", "System", None, QtGui.QApplication.UnicodeUTF8))
        self.shutdown1Button.setText(QtGui.QApplication.translate("guiDlg", "shutdown\n"
"NUC1", None, QtGui.QApplication.UnicodeUTF8))
        self.reset1Button.setText(QtGui.QApplication.translate("guiDlg", "reset\n"
"NUC1", None, QtGui.QApplication.UnicodeUTF8))
        self.wifi1.setText(QtGui.QApplication.translate("guiDlg", "wifi: ", None, QtGui.QApplication.UnicodeUTF8))
        self.shutdown2Button.setText(QtGui.QApplication.translate("guiDlg", "shutdown\n"
"NUC2", None, QtGui.QApplication.UnicodeUTF8))
        self.reset2Button.setText(QtGui.QApplication.translate("guiDlg", "reset\n"
"NUC2", None, QtGui.QApplication.UnicodeUTF8))
        self.wifi2.setText(QtGui.QApplication.translate("guiDlg", "wifi: ", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("guiDlg", "FEATURES", None, QtGui.QApplication.UnicodeUTF8))
        self.featureNavigation.setText(QtGui.QApplication.translate("guiDlg", "navitation", None, QtGui.QApplication.UnicodeUTF8))
        self.featureManupulation.setText(QtGui.QApplication.translate("guiDlg", "manipulation", None, QtGui.QApplication.UnicodeUTF8))
        self.featureSpeech.setText(QtGui.QApplication.translate("guiDlg", "TTS/ASR", None, QtGui.QApplication.UnicodeUTF8))
        self.featureSystem.setText(QtGui.QApplication.translate("guiDlg", "system", None, QtGui.QApplication.UnicodeUTF8))

